language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
  - source

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save
# 缓存依赖，节省持续集成时间
cache:
  yarn: true
  directories:
    - node_modules
    - themes

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "cherrymeteor"
  - git config user.email "cherrymeteor@outlook.com"
  - sed -i "s~https://github.com/cherrymeteor/cherrymeteor.github.io.git~https://${ACCESS_TOKEN}@github.com/cherrymeteor/cherrymeteor.github.io.git~" _config.yml
  - hexo deploy