language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
  - source

# Start: Build Lifecycle
install:
  - npm install

cache:
  directories:
    - node_modules
    - live2d_models

before_script:
  - sed -i "s~{github_client_id}~${github_client_id}~" ./themes/next/_config.yml
  - sed -i "s~{github_client_secret}~${github_client_secret}~" ./themes/next/_config.yml

script:
  - hexo clean
  - hexo generate
  # - hexo lc-counter register baaas18vGYfaega ggsdfaeas12b31saY&

after_script:
  - sed -i "s~https://github.com/cherrymeteor/cherrymeteor.github.io.git~https://${ACCESS_TOKEN}@github.com/cherrymeteor/cherrymeteor.github.io.git~" _config.yml
  - hexo deploy