language: node_js
node_js: stable
os: linux

branches:
  only:
  - source

install:
  - npm install

git:
  submodules: true

cache:
  directories:
    - node_modules
    # - live2d_models

before_script:
  - sed -i "s~{github_client_id}~${github_client_id}~" ./themes/next/_config.yml
  - sed -i "s~{github_client_secret}~${github_client_secret}~" ./themes/next/_config.yml
  - sed -i "s~{leancloud_account}~${leancloud_account}~" _config.yml
  - sed -i "s~{leancloud_password}~${leancloud_password}~" _config.yml
  - sed -i "s~https://github.com/orangejuice/orangejuice.github.io.git~https://${ACCESS_TOKEN}@github.com/orangejuice/orangejuice.github.io.git~" _config.yml

script:
  - hexo clean
  - hexo generate
  # - hexo lc-counter register baaas18vGYfaega ggsdfaeas12b31saY&

after_script:
  - hexo deploy